--[[
 !!!! !   !   !   !!!!   !!!  !   !         !   !!!!  !   ! !!!!! !   !  
!     !   !  ! !  !   ! !   ! !   !        ! !  !   ! !! !!   !   !!  !      
 !!!  !!!!! !   ! !   ! !   ! ! ! !       !   ! !   ! ! ! !   !   ! ! ! 
    ! !   ! !!!!! !   ! !   ! !! !!       !!!!! !   ! !   !   !   !  !!         
!!!!  !   ! !   ! !!!!   !!!  !   !       !   ! !!!!  !   ! !!!!! !   !  
]]
--created by shadow @ijs274
--[[
shadow admin is a costume built admin systems i made for my own games.
it has one good feature: it has hidden admin no water marks nothing.
_   _ _____ ____  ____  _____ _   _         _   ____  _   _ _____ _   _
_   _   _   _   _ _   _ _     __  _        _ _  _   _ __ __   _   __  _
_____   _   _   _ _   _ ___   _ _ _       _   _ _   _ _ _ _   _   _ _ _
_   _   _   _   _ _   _ _     _  __       _____ _   _ _   _   _   _  __
_   _ _____ ____  ____  _____ _   _       _   _ ____  _   _ _____ _   _

--use settings module to change the settings
--this is designed to be readable so feel free to change anything
--do not move any of shadow admins children to anything only make sure shadow admin the folder
is in the workspace
]]

